_BASE_: "template.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedUnrolledCNN"
  UNROLLED:
    NUM_UNROLLED_STEPS: 8
    NUM_RESBLOCKS: 2
    NUM_FEATURES: 128
    DROPOUT: 0.
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "none"
      ORDER: ("act", "conv")
AUG_TRAIN:
  UNDERSAMPLE:
    ACCELERATIONS: (2,)
    CALIBRATION_SIZE: 20
    CENTER_FRACTIONS: []
    NAME: PoissonDiskMaskFunc
SOLVER:
  OPTIMIZER: "Adam"
  LR_SCHEDULER_NAME: ""
  TRAIN_BATCH_SIZE: 4
  GRAD_ACCUM_ITERS: 4
  TEST_BATCH_SIZE: 12
  BASE_LR: 1e-4
OUTPUT_DIR: f"results://mri-recon/mridata-3dfse-knee/unrolled_{MODEL.UNROLLED.NUM_UNROLLED_STEPS}/{AUG_TRAIN.UNDERSAMPLE.NAME}/{AUG_TRAIN.UNDERSAMPLE.ACCELERATIONS}x/"
VERSION: 1